### ISSUE TITLE
Newsletter signup typo

### ISSUE THREAD

**Issue by annaredbond** [Flagsmith/flagsmith-website#10]
Signing up for the newsletter from the link at the bottom of [this blog post](https://flagsmith.com/blog/customer-interview-with-jindrich-kubat/) gives a typo in the "successful" message. 
<img width="410" alt="image" src="https://user-images.githubusercontent.com/127777934/225434722-22eccbde-a1fe-4fa8-a10a-590e3488e656.png">

**Comment by dabeeeenster** [comment]
OK fixed in https://github.com/Flagsmith/flagsmith-website/commit/5db2e58ab0180ba9b44abdc109b87679604c634c
