### ISSUE TITLE
SEO / Transfer Broken Links / Meta

### ISSUE THREAD

**Issue by kyle-ssg** [Flagsmith/flagsmith-website#18]
The sitemap of the original site can act as a reference to what has been missed. Here are the 2 to compare

https://www.flagsmith.com/sitemap.xml
https://website-flagsmith.vercel.app/sitemap.xml (original)

We need to add any missing pages that were in the original sitemap e.g.

https://flagsmith.com/overview/
https://www.flagsmith.com/launchdarkly-alternative

**Comment by deadsiemens** [comment]
- Implement /flagsmith-vs-unleash 
- Transfer SEO and Meta for Blogs and Podcasts
