### ISSUE TITLE
HLJS Console errors

### ISSUE THREAD

**Issue by kyle-ssg** [Flagsmith/flagsmith-website#19]
We seem to be getting some errors in the console
![image](https://github.com/Flagsmith/flagsmith-website/assets/8608314/5e47e968-d5be-4317-a55e-4a82cb77aff8)

**Comment by deadsiemens** [comment]
As I understand ERR_BLOCKED_BY_CLIENT caused due to the extensions installed within Chrome (Ad Blocker)
Other errors are fixed
