### ISSUE TITLE
Connect to GSC

### ISSUE THREAD

**Issue by annaredbond** [Flagsmith/flagsmith-website#26]
Akveo mentioned running into domain verification issues on their side, and were unable to connect to GSC. This needs to be resolved

**Comment by dabeeeenster** [comment]
GSC?

**Comment by dabeeeenster** [comment]
Oh google search console!

**Comment by deadsiemens** [comment]
Hi! Please, check a fast "How to" guide
https://www.koozai.com/blog/analytics/how-to-link-google-analytics-4-ga4-to-google-search-console-gsc/

**Comment by annaredbond** [comment]
This should be done, however I don't see it in the Reports section. @deadsiemens can you confirm this is connected correctly?

**Comment by deadsiemens** [comment]
Everything is correct. We can see connection 
<img width="1228" alt="Screenshot 2023-07-13 at 18 27 36" src="https://github.com/Flagsmith/flagsmith-website/assets/79444119/f5c4541b-daeb-4c9d-be35-8eab3123b72b">
