### ISSUE TITLE
Contact Us button does not work in app

### ISSUE THREAD

**Issue by annaredbond** [Flagsmith/flagsmith-website#29]
![image](https://github.com/Flagsmith/flagsmith-website/assets/127777934/1135095a-19fe-4823-a2be-632548292e1b)

This is when you log in on app.flagsmith.com -  https://app.flagsmith.com/projects#

**Comment by annaredbond** [comment]
@dabeeeenster @kyle-ssg  Relaying a message that this is outside of Akveo's scope since they can't access the app, so this will be in our to-do list

**Comment by dabeeeenster** [comment]
@kyle-ssg  this code no longer works - maybe it was related to the Zendesk > crisp migration? Any ideas? 
<img width="756" alt="image" src="https://github.com/Flagsmith/flagsmith-website/assets/173290/ce41edb4-33ff-45ea-8950-bae0217cedab">
