### ISSUE TITLE
Spam from Contact Us Form

### ISSUE THREAD

**Issue by annaredbond** [Flagsmith/flagsmith-website#31]
We are receiving a lot of spammy submissions on the contact us form, which needs mitigating. This might be a Captcha or another fix.

**Comment by deadsiemens** [comment]
Was decided to add a captcha

**Comment by dabeeeenster** [comment]
Wait wait wait please don't do this until we discuss on the next call

**Comment by annaredbond** [comment]
@dabeeeenster Should Akveo leave this one for now?

**Comment by dabeeeenster** [comment]
Lets close this until we have more data
