### ISSUE TITLE
Podcast image feed for episodes

### ISSUE THREAD

**Issue by annaredbond** [Flagsmith/flagsmith-website#35]
In Wordpress something was set up to pull the guest, author, company logo, and quote fields into the podcast images. What do we need to do to get this set up in Webflow as well? 

![image](https://github.com/Flagsmith/flagsmith-website/assets/127777934/77c88465-69ec-4bbe-ad8c-2bb3fc86b695)

If this is already setup, please close. 

@deadsiemens

**Comment by deadsiemens** [comment]
The fields for this purpose begin with "Invited Person"
<img width="460" alt="Screenshot 2023-07-11 at 11 27 04" src="https://github.com/Flagsmith/flagsmith-website/assets/79444119/82cd27d9-07a8-41af-8d53-bdcd3e283296">

**Comment by deadsiemens** [comment]
<img width="419" alt="Screenshot 2023-07-11 at 11 28 45" src="https://github.com/Flagsmith/flagsmith-website/assets/79444119/f2133a73-0173-4ab0-b085-992c7138f167">
